function intKWs = abaInpInteraction()
fricCoeef = '0.4514';
intKWs = [...
    '** INTERACTION PROPERTIES\n'...
    '** \n'...
    '*Surface Interaction, name=IntProp-1\n'...
    '*Friction\n'...
    sprintf('%s,\n', fricCoeef)...
    '*Surface Behavior, pressure-overclosure=HARD\n'...
    '** \n'...
    '** INTERACTIONS\n'...
    '** \n'...
    '** Interaction: Int-1\n'...
    '*Contact, op=NEW\n'...
    '*Contact Inclusions, ALL EXTERIOR\n'...
    '*Contact Property Assignment\n'...
    ' ,  , IntProp-1\n'...
    '** ----------------------------------------------------------------\n'...
    ];

end