function abaInpStep(fid, mSFactor)
% Print Abaqus .inp step part
% input fid:        File ID
% input mSFactor:   Mass scaling factor (min step time)

% fileName = 'printInpTemp';
% fid=fopen(sprintf('%s.inp',fileName),'wW');
% mSFactor = 5e-05;

% Print Heading of step section
fprintf(fid, ...
    ['** STEP: Step-1\n'...
    '** \n'...
    '*Step, name=Step-1, nlgeom=YES\n'...
    '*Dynamic, Explicit\n'...
    ', 1.\n'...
    '*Bulk Viscosity\n'...
    '0.06, 1.2\n']);

% Print mass scaling
fprintf(fid, [...
    '** Mass Scaling: Semi-Automatic\n'...
    '**               Whole Model\n'...
    ]);
fprintf(fid, '*Fixed Mass Scaling, dt=%f, type=below min\n', mSFactor);



% Print Ending of step section
fprintf(fid, '** \n');
fprintf(fid, '** ----------------------------------------------------------------\n');
% fclose(fid);
end