function abaInpBC(fid)
% Print Abaqus .inp material part
% input fid:        File ID

% fileName = 'printInpTemp';
% fid=fopen(sprintf('%s.inp',fileName),'wW');

% Print Heading of element control section
fprintf(fid, '** ----------------------------------------------------------------\n');
fprintf(fid, '** \n');

outputKWs = [...
    '** BOUNDARY CONDITIONS\n'...
    '** \n'...
    '** Name: BC-1 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    'BoneTop, 3, 3, -2.5\n'...
    '** Name: BC-2 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    'BoneBot, 1, 1\n'...
    'BoneBot, 2, 2\n'...
    'BoneBot, 3, 3\n'...
    'BoneBot, 4, 4\n'...
    'BoneBot, 5, 5\n'...
    'BoneBot, 6, 6\n'...
    ];
fprintf(fid, outputKWs);


% Print Ending of element control section
fprintf(fid, '** \n');
fprintf(fid, '** ----------------------------------------------------------------\n');
% fclose(fid);
end