function abaInpBC()

BCKWs = [...
    '*Amplitude, name=Amp-1, definition=SMOOTH STEP\n'...
    '             0.,              0.,              1.,              1.'
    '** BOUNDARY CONDITIONS\n'...
    '** \n'...
    '** Name: BC-1 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    'ScrewTopRef, 3, 3, 2.5\n'...
    '** Name: BC-2 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    '_PickedSet15, 1, 1\n'...
    '_PickedSet15, 2, 2\n'...
    '_PickedSet15, 3, 3\n'...
    '_PickedSet15, 4, 4\n'...
    '_PickedSet15, 5, 5\n'...
    '_PickedSet15, 6, 6\n'...
    '** \n'...
    ];

end