function abaInpOutReq(fid)
% Print Abaqus .inp material part
% input fid:        File ID

% fileName = 'printInpTemp';
% fid=fopen(sprintf('%s.inp',fileName),'wW');

% Print Heading of output request section
fprintf(fid, '** ----------------------------------------------------------------\n');
fprintf(fid, '** \n');

outputKWs = [...
    '** OUTPUT REQUESTS\n'...
    '** \n'...
    '*Restart, write, number interval=1, time marks=NO\n'...
    '** \n'...
    '** FIELD OUTPUT: F-Output-1\n'...
    '** \n'...
    '*Output, field, number interval=5, time marks=YES\n'...
    '*Node Output\n'...
    'U\n'...
    '*Element Output, directions=NO\n'...
    'DAMAGEC, DAMAGESHR, DAMAGET, LE\n'...
    'STATUS\n'...
    '*Contact Output\n'...
    'CSTRESS, \n'...
    '** \n'...
    '** HISTORY OUTPUT: H-Output-2\n'...
    '** \n'...
    '*Output, history\n'...
    '*Node Output, nset=ScrewTopRef\n'...
    'RF3, U3, UR3\n'...
    '** \n'...
    '** HISTORY OUTPUT: H-Output-1\n'...
    '** \n'...
    '*Output, history, variable=PRESELECT\n'...
    '*End Step\n'...
    ];
fprintf(fid, outputKWs);


% Print Ending of output request section
fprintf(fid, '** \n');
fprintf(fid, '** ----------------------------------------------------------------\n');
% fclose(fid);
end