function abaInpBC(fid, displacement)
% Print Abaqus .inp material part
% input fid:        File ID

% fileName = 'printInpTemp';
% fid=fopen(sprintf('%s.inp',fileName),'wW');

% Print Heading of element control section
fprintf(fid, '** ----------------------------------------------------------------\n');
fprintf(fid, '** \n');

outputKWs = [...
    '** BOUNDARY CONDITIONS\n'...
    '** \n'...
    '** Name: BC-1 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    'ScrewTopRef, 3, 3, %f\n'...
    '** Name: BC-2 Type: Displacement/Rotation\n'...
    '*Boundary, amplitude=Amp-1\n'...
    'BoneSide, 1, 1\n'...
    'BoneSide, 2, 2\n'...
    'BoneSide, 3, 3\n'...
    'BoneSide, 4, 4\n'...
    'BoneSide, 5, 5\n'...
    'BoneSide, 6, 6\n'...
    ];
fprintf(fid, outputKWs, displacement);


% Print Ending of element control section
fprintf(fid, '** \n');
fprintf(fid, '** ----------------------------------------------------------------\n');
% fclose(fid);
end