function abaInpInteraction(fid, fricCoeef)
% Print Abaqus .inp step part
% input fid:        File ID
% input mSFactor:   Mass scaling factor (min step time)

% fileName = 'printInpTemp';
% fid=fopen(sprintf('%s.inp',fileName),'wW');

intKWs = [...
    '** ----------------------------------------------------------------\n'...
    '** \n'...
    '** INTERACTION PROPERTIES\n'...
    '** \n'...
    '*Surface Interaction, name=IntProp-1\n'...
    '*Friction\n'...
    sprintf('%f,\n', fricCoeef)...
    '*Surface Behavior, pressure-overclosure=HARD\n'...
    '** \n'...
    '** INTERACTIONS\n'...
    '** \n'...
    '** Interaction: Int-1\n'...
    '*Contact, op=NEW\n'...
    '*Contact Inclusions, ALL EXTERIOR\n'...
    '*Contact Property Assignment\n'...
    ' ,  , IntProp-1\n'...
    '** \n'...
    '** ----------------------------------------------------------------\n'
    ];

fprintf(fid, intKWs);

% fclose(fid);
end