function [] = plotMesh(elements, vertCoor, transPara, lineStyle)
% triSurfs = [];
if size(elements,2) == 8
    triSurfs = zeros(12*size(elements,1),3);
    for ii=1: 1: size(elements,1)
        triSurfs(ii*12-11:ii*12,:) = [...
            [elements(ii,1),elements(ii,2),elements(ii,3)];...
            [elements(ii,1),elements(ii,3),elements(ii,4)];...
            [elements(ii,5),elements(ii,6),elements(ii,7)];...
            [elements(ii,5),elements(ii,7),elements(ii,8)];...
            [elements(ii,1),elements(ii,2),elements(ii,6)];...
            [elements(ii,1),elements(ii,6),elements(ii,5)];...
            [elements(ii,2),elements(ii,3),elements(ii,7)];...
            [elements(ii,2),elements(ii,7),elements(ii,6)];...
            [elements(ii,1),elements(ii,8),elements(ii,5)];...
            [elements(ii,1),elements(ii,4),elements(ii,8)];...
            [elements(ii,4),elements(ii,7),elements(ii,8)];...
            [elements(ii,4),elements(ii,3),elements(ii,7)];...
            ];
    end
elseif size(elements,2) == 10 || size(elements,2) == 4
    triSurfs = zeros(4*size(elements,1),3);
    for ii=1: 1: size(elements,1)
        triSurfs(ii*4-3:ii*4,:) = [...
            [elements(ii,1),elements(ii,2),elements(ii,3)];...
            [elements(ii,1),elements(ii,3),elements(ii,4)];...
            [elements(ii,1),elements(ii,2),elements(ii,4)];...
            [elements(ii,2),elements(ii,3),elements(ii,4)];...
            ];
    end
end
trisurf(triSurfs,vertCoor(:,2),vertCoor(:,3),vertCoor(:,4),'FaceAlpha',transPara,'LineStyle',lineStyle,'FaceColor',[0.85 0.85 0.85]);
axis equal
% toc

end