clear all
close all
clc

A = [...
    '*Part, name=Bone\n'...
    '*End Part\n'...
    '**\n'...
    '**\n'...
    '** ASSEMBLY\n'...
    '**\n'...
    '*Assembly, name=Assembly\n'...
    '**\n'...
    ];