function stepKWs = abaInpStep()
mSFactor = '5e-05';
stepKWs = [...
    '** \n'...
    '** STEP: Step-1\n'...
    '** \n'...
    '*Step, name=Step-1, nlgeom=YES\n'...
    '*Dynamic, Explicit\n'...
    ', 1.\n'...
    '*Bulk Viscosity\n'...
    '0.06, 1.2\n'...
    '** Mass Scaling: Semi-Automatic\n'...
    '**               Whole Model\n'...
    sprintf('*Fixed Mass Scaling, dt=%s, type=below min\n', mSFactor)...
    '** \n'...
    ];
end